version: '3'
services:
  api:
    build:
      dockerfile: DockerfileJava
    container_name: api_mayoo
    restart: always
    depends_on: 
      - db
      - adminer
    ports:
      - "80:8080"
    environment:
      - PORT=${API_PORT}
      - HOSTNAME_DB=db
      - PORT_DB=3306
      - USERNAME_DB=${DB_USER}
      - PASSWORD_DB=${DB_PASSWORD}
      - DB=${DB_NAME}
  db:
    image: mariadb:10.6.13-focal
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
